title: My first website
baseURL: https://iraparsons.com
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content
    title: Ira Parsons
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/IraParsons
    - name: github
      url: https://github.com/irap93
    - name: linkedin
      url: https://www.linkedin.com/in/ira-parsons-00b33a79/
  author: ''
  background_color_class: bg-black
  description: Movement ecology
  favicon: ''
  recent_posts_number: 3
  site_logo: ''
  text_color: ''
