# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-C52R3XCF4V'

menu:
# - {name: 'Interesting Facts',  url: 'facts'}
- {name: 'Blog', url: 'blog'}
- {name: 'About',              url: 'about'}
- {name: 'CV',       url: 'CV'}
# - {name: 'Documentation',      url: 'documentation'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/IraParsons'}
- {icon: 'github', link: 'https://github.com/irap93'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/ira-parsons/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=RJZksf0AAAAJ&hl=en'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'envelope', link:   'mailto:ira.parsons@sdstate.edu'}
- {icon: 'puzzle-piece', link: 'https://www.researchgate.net/profile/Ira-Parsons/'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
