# **Ira Lloyd Parsons**

Mississippi State University, Thomson Hall · Mississippi State, MS 39762 · 913-565-0896 · ilp28@msstate.edu

**Education**

Doctor of Philosophy in Forest Resources, Mississippi State University December 2022

concentration: Wildlife, Fisheries and Aquaculture, GPA 4.00

Mississippi State University, Mississippi State, Mississippi, 39762

Dissertation Title: Animal Husbandry in the 21 st Century: Understanding beef cattle grazing systems ecology using precision technology_

Chapters: Thesis Objective: Demonstrate prospective uses of tracking collars and accelerometers to study fine-scale movement and behaviors related to animal cattle growth/production, energy expenditure, and pasture space use given landscape resource distribution. and quantify relationship between animal movement, behavior, energetics, growth, and production.

1. Utility of using accelerometers to track animal behavior, energy expenditure, and energy intake in response to resource distribution across the pastoral landscape.
2. Aiming for the optimum: examining complex relationships between sampling regime, sampling density, and landscape complexity to accurately model resource availability – In review
3. Developing algorithms to identify spurious data-points and model animal growth using automated walk-over-weigh system to track daily weight change and growth in grazing Brangus steers – In Review

Master of Science in Animal Science, Texas A&amp;M University GPA 3.24 May 2018

GPA 3.24Texas A&amp;M University, College Station, Texas, 77843

Thesis Title: _Prediction of feed intake and feed efficiency in feedlot steers
 based on phenotypic associations with feeding behavior and carcass ultrasound traits_

Bachelor of Science in Grain Science and Industry and, Feed Science and Management, August 2015

Kansas State University

GPA: 3.67, Major: GPA: 3.78

Kansas State University, Manhattan, Kansas, 66506

**Professional Presentations and ArticlesPublications**

Published

1. Kayser, William W. C., G.E. Carstens, **I. L. Parsons** , K.E. Washburn, S.D. Lawdon, W.E. Pinchak, E. Chevaux, and A.L. 2020. Skidmore. Efficacy of statistical process control procedures to identify deviations in continuously measured physiologic and behavioral variables in beef steers experimentally challenged with _Mannheimia haemolytica_. Journal of Animal Science. 2020 volume:page-page
2. **Parsons, I.L.** , J.R. Johnson, W.C. Kayser, and G.E. Carstens. 2019. Characterization of feeding behavior traits in steers with divergent residual feed intake consuming a high-grain diet. Journal of Animal Science. 2019volume:page-page
3. Kayser, W.C., G.E. Carstens, **I.L. Parsons** , T.H. Welsh, K.E. Washburn, S.D. Lawhon, W.E. Pinchak, J.T. Richeson, E. Chevaux, and A.L. Skidmore. 2019. Effects of Mannheimia haemolytica challenge with or without supplementation of _Saccharomyces cerevisiae boulardii_ strain CNCM I1079 on immune upregulation and behavior in beef steers. Journal of Animal Science. 2019volume:page-page

_In Review._

1. **Parsons, I.L.** , Melanie M.R. Boudreau, Brandi B.B. Karisch, Amanda A.E. Stone, Durham D. Norman, Stephen S.L. Webb, Kristine K.O. Evans, and Garrett G.M. Street. Aiming for the optimum: examining complex relationships between sampling regime, sampling density, and landscape heterogeneity to accurately model resource availability. _Submitted to Journal of Landscape Ecology._ 2021. _In review._

_In Preparation (full draft available)_

1. Developing algorithms to identify spurious data-points and model animal growth using automated walk-over-weigh system to track daily weight change and growth in grazing Brangus steers. – _Under collaboratorIn rReview_

**International, National, and Regional Meeting Presentations**

1. **Ira L. Parsons** , B.B. Karisch, S.L. Webb, A.E. Stone, C.C. Catrett, J.E. Dentinger, D.A. Norman, &amp;and G.M. Street. 2021. GPS tracking collars and accelerometers provide detailed tracking of foraging behavior and space use in grazing steers in Bermudagrass and Tall Fescue pasture. Journal of Animal Science 99. Supplement 3. Louisville, KY. July 2021
2. Catrett, C.C., **I.L. Parsons** , J.E. Dentinger, D.A. Norman, S.L. Webb, A.E. Stone, G.M. Street, B. B. Karisch. Identifying behaviors and the &#39;normal&#39; daily ethogram using accelerometers on grazing animals. Journal of Animal Science 99. Supplement 3 Louisville, KY. July 2021
3. Johnson, J.R., G. E. Carstens, **I.L. Parsons** , L.O. Tedeschi, and J. Deeb. 2019. Characterization of feeding-behavior patterns and application of chemometrics to predict residual feed intake based on feeding-behavior traits in growing Holstein heifers. Southern Section Animal Science Meeting, Oklahoma City, OK. 25 January 2019.
4. **Parsons, I.L.,** G.E. Carstens, C.A. Olson, J.R. Johnson, W.C. Kayser, D.S. Hale, and R.K. Miller. 2018. Effects of residual feed intake classification on carcass-value traits in finishing cattle. International Congress of Meat Science and Technology, Melbourne, Australia., August 2018.

1. **Parsons, I.L.,** G.E. Carstens, J.R. Johnson, W.C. Kayser, and C.A. Olson. 2018. Application of Partial Least Squares regression to predict feed efficiency based on feeding behavior in beef cattle. Plains Nutrition Council, San Antonio, TX, April 2018..
2. **Parsons, I.L.** , C.L. Daigle, and G.E. Carstens. 2018. Consistently efficient: the use of feeding behavior to identify efficient beef cattle. International Symposium of Applied Animal Ethologist, Prince Edward Island, Canada. July, 2018.
3. **Parsons, I.L.,** G.E. Carstens, W.C. Kayser, and J. R. Johnson. 2018. Application of partial least squares regression to predict feed efficiency based on feeding behavior patterns in beef cattle. International Symposium on the Nutrition of Herbivores, Clermont-Ferrand, France. September 2018. Ref. # 0401
4. **Parsons, I.L.,** W.C. Kayser, and G.E. Carstens. 2018. Application of partial least squares regression to predict feed efficiency based on feeding behavior patterns in beef cattle. Southern Section Animal Science Meeting, Fort Worth, TX. 6 February 2018. Abstract #25

**Grantsmanship**

Street, G.M., B.B. Karisch. Observing the unobservable: identifying behaviors and the &#39;normal&#39; daily ethogram using accelerometers and video cameras. CALS/MAFES 2020 Undergraduate Research Program. $$$$._ **Ira Parsons** _ _Graduate Research Assistant developed, wrote, and supervised the project._

**References**

Dr. Garrett Street – Assistant Professor, Wildlife, Fisheries, and Aquaculture

Mississippi State University, Box 9680, Mississippi State, MS 39762

Phone: (662) 325-5801; [gms246@msstate.edu](mailto:gms246@msstate.edu)

Dr. Brandi Karisch – Associate Professor, Extension Beef Cattle Specialist

Mississippi State University, Box 9815, Mississippi State, MS 39762

Phone: (662) 325-7465; [brandi.karisch@msstate.edu](mailto:brandi.karisch@msstate.edu)

Page 2